In [1]:
import pandas as pd 
import numpy as np
import plotly.express as px
import os
import warnings
import re

warnings.filterwarnings("ignore")
os.listdir('data')

['products_asos.csv']

In [2]:
data = pd.read_csv("data/products_asos.csv", on_bad_lines= 'skip')
data.sample(5)

,url,name,size,category,price,color,sku,description,images
17742,https://www.asos.com/lindex/lindex-poly-blend-...,Lindex poly blend seamless rib moulded push up...,"XS - UK 6 - Out of stock,S - UK 8 - Out of sto...",Lindex poly blend seamless rib moulded push up...,20.00,Dusky Pink,117345087.0,[{'Product Details': 'Lingerie & Nightwear by ...,['https://images.asos-media.com/products/linde...
18639,https://www.asos.com/adidas-originals/adidas-o...,adidas Originals Pride printed track pants in ...,"XXL - W54 - Out of stock,XS - W36,XL - W52,L -...",adidas Originals Pride printed track pants in ...,55.00,Black,114995469.0,[{'Product Details': 'Joggers by adidas Origin...,['https://images.asos-media.com/products/adida...
19151,https://www.asos.com/asos-tall/asos-design-tal...,ASOS DESIGN Tall long sleeve striped t-shirt i...,"UK 4,UK 6,UK 8,UK 10,UK 12,UK 14,UK 16,UK 18,U...",ASOS DESIGN Tall long sleeve striped t-shirt i...,14.00,Navy/white,101794958.0,[{'Product Details': 'T-shirt by ASOS TallFor ...,['https://images.asos-media.com/products/asos-...
5085,https://www.asos.com/miss-selfridge/miss-selfr...,Miss Selfridge Chartreuse Puff Sleeve Jumper ...,"XS - UK 4-6 - Out of stock,S - UK 8-10,M - UK ...",Miss Selfridge Chartreuse Puff Sleeve Jumper ...,Now 13.99,CHARTREUSE,105099328.0,[{'Product Details': 'Jumper by Miss Selfridge...,['https://images.asos-media.com/products/miss-...
22636,https://www.asos.com/asos-design/asos-design-k...,ASOS DESIGN kimono in premium floral burnout,"UK 4,UK 6,UK 8,UK 10,UK 12,UK 14,UK 16,UK 18",ASOS DESIGN kimono in premium floral burnout,Now 43.50,FLORAL BURNOUT,121959010.0,[{'Product Details': 'Tops by ASOS DESIGNCompl...,['https://images.asos-media.com/products/asos-...

In [3]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 30845 entries, 0 to 30844
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   url          30827 non-null  str
 1   name         30827 non-null  str
 2   size         30827 non-null  str
 3   category     30827 non-null  str
 4   price        30827 non-null  str
 5   color        30827 non-null  str
 6   sku          30827 non-null  float64
 7   description  30827 non-null  str
 8   images       30827 non-null  str
dtypes: float64(1), str(8)
memory usage: 2.1 MB

In [4]:
data['price'] = pd.to_numeric(data['price'], errors='coerce') #Convertimos a número el precio a número y obligamos a NaN si errores
data.dropna(subset=['price'], inplace= True) # Quitamos los NaNs

print("Data Shape: " + str(data.shape))

Data Shape: (18378, 9)

In [5]:
# Problema a resolver: Analizar el precio para saber cuanto estan perdiendo por no tener productos en stockç

# Primero limpiamos la columna description para obtener la marca del producto usando la url para obtener la marca
def get_brand_from_url(url):
    match = re.search(r'asos\.com/([^/]+)/', url)

    if match:
        return match.group(1)

    return None

data["brand"] = data["url"].apply(get_brand_from_url)

In [6]:
data.sample(5)

,url,name,size,category,price,color,sku,description,images,brand
3738,https://www.asos.com/pimkie/pimkie-cropped-v-n...,Pimkie cropped v neck cardigan in beige,"XS - UK 6,S - UK 8,M - UK 10,L - UK 12",Pimkie cropped v neck cardigan in beige,20.00,Beige,125773534.0,[{'Product Details': 'Jumpers & Cardigans by P...,['https://images.asos-media.com/products/pimki...,pimkie
30805,https://www.asos.com/new-look/new-look-puff-sl...,New Look puff sleeve midi dress with cut out d...,"UK 4 - Out of stock,UK 6 - Out of stock,UK 8 -...",New Look puff sleeve midi dress with cut out d...,29.99,White,119897018.0,[{'Product Details': 'Midi dress by New Look S...,['https://images.asos-media.com/products/new-l...,new-look
21479,https://www.asos.com/we-are-we-wear/we-are-we-...,We Are We Wear Plus Maria sarong in black,One Size,We Are We Wear Plus Maria sarong in black,20.00,Black,116420285.0,[{'Product Details': 'Tops by We Are We Wear*i...,['https://images.asos-media.com/products/we-ar...,we-are-we-wear
18299,https://www.asos.com/topshop/topshop-co-ord-sl...,Topshop co-ord slouchy oversized cuffed jogger...,"XS - UK 4-6,S - UK 8-10,M - UK 12-14,L - UK 16...",Topshop co-ord slouchy oversized cuffed jogger...,30.00,ECRU,121144912.0,[{'Product Details': 'Joggers by TopshopWelcom...,['https://images.asos-media.com/products/topsh...,topshop
29230,https://www.asos.com/vila/vila-slinky-wide-leg...,Vila slinky wide leg trouser co-ord in waterco...,"EU 34 - UK 6,EU 36 - UK 8,EU 38 - UK 10,EU 40 ...",Vila slinky wide leg trouser co-ord in waterco...,39.00,White AOP,120752596.0,[{'Product Details': 'Trousers & Leggings by V...,['https://images.asos-media.com/products/vila-...,vila

In [7]:
# Limpiamos en nombre de la marca
data["brand"] = (
    data["brand"]
    .str.replace("-", " ")
    .str.title()
)

In [8]:
# Poner en mínisculas todas los colores
def lower_string(text):
    return text.lower()

data['color'] = data['color'].apply(lower_string)

In [9]:
# Separar la variable de size 
data["size_list"] = data["size"].str.split(",")

data = data.explode("size_list")

data.head(5)

,url,name,size,category,price,color,sku,description,images,brand,size_list
0,https://www.asos.com/stradivarius/stradivarius...,New Look trench coat in camel,"UK 4,UK 6,UK 8,UK 10,UK 12,UK 14 - Out of stoc...",New Look trench coat in camel,49.99,neutral,126704571.0,[{'Product Details': 'Coats & Jackets by New L...,['https://images.asos-media.com/products/new-l...,Stradivarius,UK 4
0,https://www.asos.com/stradivarius/stradivarius...,New Look trench coat in camel,"UK 4,UK 6,UK 8,UK 10,UK 12,UK 14 - Out of stoc...",New Look trench coat in camel,49.99,neutral,126704571.0,[{'Product Details': 'Coats & Jackets by New L...,['https://images.asos-media.com/products/new-l...,Stradivarius,UK 6
0,https://www.asos.com/stradivarius/stradivarius...,New Look trench coat in camel,"UK 4,UK 6,UK 8,UK 10,UK 12,UK 14 - Out of stoc...",New Look trench coat in camel,49.99,neutral,126704571.0,[{'Product Details': 'Coats & Jackets by New L...,['https://images.asos-media.com/products/new-l...,Stradivarius,UK 8
0,https://www.asos.com/stradivarius/stradivarius...,New Look trench coat in camel,"UK 4,UK 6,UK 8,UK 10,UK 12,UK 14 - Out of stoc...",New Look trench coat in camel,49.99,neutral,126704571.0,[{'Product Details': 'Coats & Jackets by New L...,['https://images.asos-media.com/products/new-l...,Stradivarius,UK 10
0,https://www.asos.com/stradivarius/stradivarius...,New Look trench coat in camel,"UK 4,UK 6,UK 8,UK 10,UK 12,UK 14 - Out of stoc...",New Look trench coat in camel,49.99,neutral,126704571.0,[{'Product Details': 'Coats & Jackets by New L...,['https://images.asos-media.com/products/new-l...,Stradivarius,UK 12

In [10]:
# Si size contiene Out of Stock, se crea una variable booleana
data["in_stock"] = ~data["size_list"].str.contains(
    "Out of stock",
    case=False,
    na=False
)

In [11]:
# Contar nº de tallas por prenda
data["num_sizes"] = data["size"].str.count(",") + 1

# Contar las veces que se encuentra Out of Stock una talla de un producto
data["num_out_of_stock"] = data["size"].str.count("Out of stock")

# Definir un ratio de disponibilidad
data["availability_ratio"] = (
    data["num_sizes"] - data["num_out_of_stock"]
) / data["num_sizes"]

In [12]:
data.head(5)

,url,name,size,category,price,color,sku,description,images,brand,size_list,in_stock,num_sizes,num_out_of_stock,availability_ratio
0,https://www.asos.com/stradivarius/stradivarius...,New Look trench coat in camel,"UK 4,UK 6,UK 8,UK 10,UK 12,UK 14 - Out of stoc...",New Look trench coat in camel,49.99,neutral,126704571.0,[{'Product Details': 'Coats & Jackets by New L...,['https://images.asos-media.com/products/new-l...,Stradivarius,UK 4,True,8,1,0.875
0,https://www.asos.com/stradivarius/stradivarius...,New Look trench coat in camel,"UK 4,UK 6,UK 8,UK 10,UK 12,UK 14 - Out of stoc...",New Look trench coat in camel,49.99,neutral,126704571.0,[{'Product Details': 'Coats & Jackets by New L...,['https://images.asos-media.com/products/new-l...,Stradivarius,UK 6,True,8,1,0.875
0,https://www.asos.com/stradivarius/stradivarius...,New Look trench coat in camel,"UK 4,UK 6,UK 8,UK 10,UK 12,UK 14 - Out of stoc...",New Look trench coat in camel,49.99,neutral,126704571.0,[{'Product Details': 'Coats & Jackets by New L...,['https://images.asos-media.com/products/new-l...,Stradivarius,UK 8,True,8,1,0.875
0,https://www.asos.com/stradivarius/stradivarius...,New Look trench coat in camel,"UK 4,UK 6,UK 8,UK 10,UK 12,UK 14 - Out of stoc...",New Look trench coat in camel,49.99,neutral,126704571.0,[{'Product Details': 'Coats & Jackets by New L...,['https://images.asos-media.com/products/new-l...,Stradivarius,UK 10,True,8,1,0.875
0,https://www.asos.com/stradivarius/stradivarius...,New Look trench coat in camel,"UK 4,UK 6,UK 8,UK 10,UK 12,UK 14 - Out of stoc...",New Look trench coat in camel,49.99,neutral,126704571.0,[{'Product Details': 'Coats & Jackets by New L...,['https://images.asos-media.com/products/new-l...,Stradivarius,UK 12,True,8,1,0.875

In [13]:
data.info()

<class 'pandas.DataFrame'>
Index: 120923 entries, 0 to 30844
Data columns (total 15 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   url                 120923 non-null  str
 1   name                120923 non-null  str
 2   size                120923 non-null  str
 3   category            120923 non-null  str
 4   price               120923 non-null  float64
 5   color               120923 non-null  str
 6   sku                 120923 non-null  float64
 7   description         120923 non-null  str
 8   images              120923 non-null  str
 9   brand               120923 non-null  str
 10  size_list           120923 non-null  str
 11  in_stock            120923 non-null  bool
 12  num_sizes           120923 non-null  int64
 13  num_out_of_stock    120923 non-null  int64
 14  availability_ratio  120923 non-null  float64
dtypes: bool(1), float64(3), int64(2), str(9)
memory usage: 14.0 MB

In [14]:
# REALIZAR AGRUPACIONES Y PLOTS PARA VER LOS DATOS

brand_counts = (
    data.groupby("brand")
        .size()
        .sort_values(ascending=False)
        .reset_index()
)

fig = px.bar(
    brand_counts,
    x = 'brand',
    y = 0,
    color= 'brand',
    title= "Which brands have the most products?",
    template = 'simple_white'
)

fig.show()

In [15]:
brand_summary = (
    data.groupby("brand")
        .agg(
            num_products=("sku", "count"),
            avg_price=("price", "mean"),
            median_price=("price", "median"),
            avg_availability=("availability_ratio", "mean")
        )
        .sort_values("num_products", ascending=False)
        .reset_index()
)

fig = px.bar(
    brand_summary,
    x = 'brand',
    y = 'avg_availability',
    color = "brand",
    title= "Average Availability of brands",
    template = 'simple_white'
    
)

fig.show()

In [ ]:
fig = px.scatter(
    brand_summary,
    x = 'median_price',
    y = 'avg_availability',
    color = 'brand',
    title= "Average Price of brands and their average availability",
    template = 'simple_white'
    
)
fig.show()

In [21]:
brand_summary.head(10)

            brand  num_products   avg_price  median_price  avg_availability
0     Asos Design         22809   40.973214         35.00          0.697707
1         Topshop          5746   51.695849         50.00          0.721197
2      Asos Curve          4790   36.256983         32.00          0.807098
3       Collusion          3235   24.485901         22.99          0.700464
4  Miss Selfridge          3134   37.213484         32.99          0.741863
5       Asos Tall          2669   39.505058         35.00          0.695766
6    Asos Edition          2535  130.580276        110.00          0.771598
7           Monki          2523   31.743559         30.00          0.617519
8        New Look          2443   27.097826         25.99          0.555465
9     Asos Petite          2368   40.200494         36.00          0.713260

In [22]:
category_summary = (
    data.groupby("category")
        .agg(
            products=("sku", "count"),
            avg_price=("price", "mean"),
            median_price=("price", "median")
        )
        .sort_values("products", ascending=False)
)

In [23]:
availability_by_brand = (
    data.groupby("brand")
        .agg(
            avg_availability=("availability_ratio", "mean")
        )
        .sort_values("avg_availability")
        .reset_index()
)

fig = px.bar(
    availability_by_brand,
    x = 'brand',
    y = 'avg_availability',
    color = 'brand',
    title = 'Which brands are frequently sold out?',
    template = 'simple_white'
)
fig.show()

In [24]:
price_by_brand = (
    data.groupby("brand")
        .agg(
            avg_price=("price", "mean"),
            median_price=("price", "median"),
            max_price=("price", "max")
        )
        .sort_values("avg_price", ascending=False)
        .reset_index()
)

fig = px.bar(
    price_by_brand,
    x = 'brand',
    y = 'avg_price',
    color = 'brand',
    title = 'Which brands are premium?',
    template = 'simple_white'
)
fig.show()

In [25]:
top_colors = (
    data.groupby("color")
        .size()
        .sort_values(ascending=False)
        .reset_index()
)

top_colors.head(5)

fig = px.bar(
    top_colors,
    x = 'color',
    y = 0,
    color = "color",
    title = 'What colors are usually sold the most?',
)
fig.show()

In [26]:
colors_price = data.groupby('color')['price'].mean().round(2).sort_values(ascending=False).reset_index()

fig = px.bar(
    colors_price,
    x = 'color',
    y = 'price',
    color = "color",
    title = 'What colors are usually sold with the highest price?',
)
fig.show()

In [27]:
data_corr = data[[
    "price",
    "num_sizes",
    "availability_ratio"
]].corr(numeric_only=True)

# Do expensive products offer more sizes?
# Are expensive products more likely to sell out?

fig = px.imshow(data_corr)
fig.show()